sudo: true
language: C++
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo add-apt-repository -y ppa:afrank/boost
      sudo apt-get update -y -qq
      sudo apt-get autoremove libboost-all-dev
      sudo apt-get install -y libboost1.57-all-dev
      sudo apt-get install -y g++-5
      sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-5  90;
      sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-5  90;
    fi
compiler:
    - clang++
install:
    - sh travis-build-and-test.sh
script:
    - cd buildgcc/test && make check && cd ../tools && make check
