sudo: true
language: C++
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install g++-4.9
compiler:
    - clang++
install:
    - sh travis-build-and-test.sh
script:
    - cd buildclang/test && make check && ../tools && make check
