sudo: true
cache: apt
language: C++

matrix:
  include:
    - os: linux
      dist: xenial
      env: CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
          - pandoc
          - libboost-all-dev
    - os: linux
      dist: xenial
      env: CXX_COMPILER=g++-8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-8
          - pandoc
          - libboost-all-dev
    - os: linux
      dist: xenial
      compiler: clang++
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
          - pandoc
          - libboost-all-dev
    - os: osx
      osx_image: xcode10.1


before_install:
  # We need to re-export CC and CXX here, because travis exports CXX=g++ or clang++ AFTER we set CXX.
  - PATH=$HOME/local/bin:$PATH
  - echo $PATH
  - if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
  - if [ -n "${CXX_COMPILER}" ]; then export CXX="${CXX_COMPILER}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install meson && pip install requests; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip && unzip -q ninja-linux.zip -d ~/bin && pyenv local 3.7 && pip3 install meson requests; fi

script:
# build restbed
  - git clone --recursive https://github.com/corvusoft/restbed.git
  - mkdir restbed/build
  - ( cd restbed/build ; cmake -DBUILD_SSL=NO -DCMAKE_INSTALL_PREFIX="$HOME/local/" .. ; make ; make install )
# build otcetera
  - export CPPFLAGS='-I${HOME}/local/include'
  - export LDFLAGS='-L${HOME}/local/library'
  - echo $CPPFLAGS
  - echo $LDFLAGS
  - meson build --prefix=$HOME/local
  - cat build/meson-logs/meson-log.txt
  - ninja -C build install
  - ninja -C build test