sudo: true
cache: apt
language: C++

matrix:
  include:
    - os: linux
      dist: bionic
      env: CXX_COMPILER=g++-8
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
          - g++-8
          - pandoc
          - libboost-all-dev
    - os: linux
      dist: bionic
      env: CXX_COMPILER=g++-9
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
          - g++-9
          - pandoc
          - libboost-all-dev
    - os: linux
      dist: bionic
      compiler: clang++
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
          - g++-9
          - pandoc
          - libboost-all-dev
# - os: osx
# osx_image: xcode10.1


before_install:
  # We need to re-export CC and CXX here, because travis exports CXX=g++ or clang++ AFTER we set CXX.
  - PATH=$HOME/local/bin:$PATH
  - echo $PATH
  - if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
  - if [ -n "${CXX_COMPILER}" ]; then export CXX="${CXX_COMPILER}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install meson && pip install requests; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip && unzip -q ninja-linux.zip -d ~/bin && pyenv local 3.7.1 && pip3 install meson; fi

script:
# build restbed
  - git clone --recursive https://github.com/corvusoft/restbed.git
  - mkdir restbed/build
  - ( cd restbed/build ; cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_TESTS=NO -DBUILD_SSL=NO -DCMAKE_INSTALL_PREFIX="$HOME/local/" .. ; make ; make install )
# build otcetera
  - export CPPFLAGS="-I${HOME}/local/include"
  - export LDFLAGS="-L${HOME}/local/lib -L${HOME}/local/library"
  - if ! meson build --prefix=$HOME/local ; then cat build/meson-logs/meson-log.txt ; exit 1 ; fi
  - ninja -C build install
# test otcetera
  - export LD_LIBRARY_PATH="${HOME}/local/lib:${HOME}/local/library"
  - if ! ninja -C build test ; then cat build/meson-logs/testlog.txt ; exit 1 ; fi
