sudo: true
language: C++
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y -qq
    - sudo apt-get install -y libboost-dev libboost-program-options-dev
    - sudo apt-get install -y g++-5
compiler:
    - clang++
install:
    - sh travis-build-and-test.sh
script:
    - cd buildclang/test && make check && cd ../tools && make check
