summarizing-taxonomy-plus-trees.pdf: summarizing-taxonomy-plus-trees.tex otcetera.bib
	latexmk -pdf summarizing-taxonomy-plus-trees.tex

node-identifiers.pdf: node-identifiers.tex otcetera.bib
	latexmk -pdf node-identifiers.tex